### ISSUE TITLE
Using different configurations per request?

### ISSUE THREAD

**Issue by joshuadelange** [mobilecause/cardconnect#14]
Hello there!

Thank you for creating this gem!

For our app we are wanting to use a different endpoint and api configure for different requests dynamically. For some clients we want to use the UAT environment, for others the production environment.

It may very well be a lack of my Ruby knowledge, but I can't figure out how to switch the CardConnect configuration while the app is running. I've tried putting the code from the initialiser in an if else statement, and it works for the first request, but when I want then make a request with the other environment, it stays stuck in the previous environment.

```
    if self.use_uat_settings?
      puts "USING UAT CC SETTINGS"
      CardConnect.configure do |config|
        config.merchant_id = ENV.fetch('UAT_CC_MERCHANT_ID')
        config.api_username = ENV.fetch('UAT_CC_API_USERNAME')
        config.api_password = ENV.fetch('UAT_CC_API_PASSWORD')
        config.endpoint = ENV.fetch('UAT_CC_ENDPOINT')
        puts "config: #{config.inspect}"
      end
    else
      puts "USING NORMAL CC SETTINGS"
      CardConnect.configure do |config|
        config.merchant_id = ENV.fetch('CC_MERCHANT_ID')
        config.api_username = ENV.fetch('CC_API_USERNAME')
        config.api_password = ENV.fetch('CC_API_PASSWORD')
        config.endpoint = ENV.fetch('CC_ENDPOINT')
        puts "config: #{config.inspect}"
      end
    end
```

Any help or direction you could point me in would be very appreciated.

Thank you!

**Comment by prashm** [comment]
It's not recommended to have your production env connect to a third party test env. So your testing/staging env should be configured to be connect to the cardconnect UAT and not your production. But if you still think you do need to it this way, you can fork out the gem and update the initialize method in CardConnect::Connection class to optionally take in config object param. Once you do that you can dynamically create CardConnect::Connection object by passing in your config obj. For example:
```
config = CardConnect::Configuration.new
if self.use_uat_settings?
      puts "USING UAT CC SETTINGS"
      config.merchant_id = ENV.fetch('UAT_CC_MERCHANT_ID')
      config.api_username = ENV.fetch('UAT_CC_API_USERNAME')
      config.api_password = ENV.fetch('UAT_CC_API_PASSWORD')
      config.endpoint = ENV.fetch('UAT_CC_ENDPOINT')
      puts "config: #{config.inspect}"
else
      puts "USING NORMAL CC SETTINGS"
      config.merchant_id = ENV.fetch('CC_MERCHANT_ID')
      config.api_username = ENV.fetch('CC_API_USERNAME')
      config.api_password = ENV.fetch('CC_API_PASSWORD')
      config.endpoint = ENV.fetch('CC_ENDPOINT')
      puts "config: #{config.inspect}"
end
connection = CardConnect::Connection.new(config)
auth_service = CardConnect::Service::Authorization.new(connection)
```

**Comment by joshuadelange** [comment]
Thank you @prashm ! We didn't need to adjust the gem itself, but your answer pointed us in the right way.
