### ISSUE TITLE
Remove `ssl: { verify: false }` in Faraday constructor

### ISSUE THREAD

**Issue by jhanggi** [mobilecause/cardconnect#3]
Why is this present in the call to `Faraday.new` in `Connection`? Is there something wrong with CardConnect's certificate? I was able to remove this and get a successful handshake/request.

If this is necessary for some cases, perhaps it would be better as a configuration option. I'm happy to put together a PR, but wanted to check in before I do the work.

Thanks for your work on this gem!

**Comment by thetizzo** [comment]
Hi!  I honestly can't remember why I set that setting that way.  I would definitely be willing to make this a configurable option with the current value as the default. 

A PR would be welcome.  Thanks! 👍
